### ISSUE TITLE
java.lang.ClassNotFoundException: com.helger.commons.traits.IGenericImplTrait

### ISSUE THREAD

**Issue by aschneebauer** [phax/erechnung.gv.at-webservice-client#1]
After building the jar, and importing to my project, each time when i call

WS200Sender stub = new WS200Sender(sWebserviceUsername, sWebservicePassword);

I got the class not found error based on AbstractWSSender

I also tried to download the jar direct from maven repository:
https://mvnrepository.com/artifact/com.helger.erechnung.gv.at/webservice-client/3.1.0

It also dont work

**Comment by phax** [comment]
You are missing the "ph-commons" dependency. What build system are you using the grab the transitive dependencies? Maven, Gradle, Ant...???

**Comment by aschneebauer** [comment]
My goal is to create a web application where clients can be maintained for e-rechnung. so i want to create a dynamic web application. i was thinking i only can include your *.jar file.

**Comment by phax** [comment]
Unfortunately, that is not enough. You need to include all the transitive dependencies to make it work. What build system are you using???

**Comment by aschneebauer** [comment]
i am starting with  maven:
Thats my current pom.xml

<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.psptirol</groupId>
	<artifactId>USPWebProject</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>

	<name>USPWebProject Maven Webapp</name>
	
	<url>http://www.example.com</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.11</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.1.0</version>
		</dependency>
		<dependency>
			<groupId>com.helger.erechnung.gv.at</groupId>
			<artifactId>webservice-client</artifactId>
			<version>3.1.0</version>
		</dependency>
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jstl</artifactId>
			<version>1.2</version>
		</dependency>

	</dependencies>

	<build>
		<finalName>USPWebProject</finalName>
		<pluginManagement>
			<plugins>
				<plugin>
					<artifactId>maven-clean-plugin</artifactId>
					<version>3.1.0</version>
					<configuration>
						<source>1.8</source>
						<target>1.8</target>
					</configuration>
				</plugin>
				
				<plugin>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.0.2</version>
				</plugin>
				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.8.0</version>
				</plugin>
				<plugin>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.22.1</version>
				</plugin>
				<plugin>
					<artifactId>maven-war-plugin</artifactId>
					<version>3.2.2</version>
				</plugin>
				<plugin>
					<artifactId>maven-install-plugin</artifactId>
					<version>2.5.2</version>
				</plugin>
				<plugin>
					<artifactId>maven-deploy-plugin</artifactId>
					<version>2.8.2</version>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>

**Comment by phax** [comment]
That looks good. If you build the application, the resulting WAR file should contain `ph-commons-9.3.6.jar`, `ph-xml-9.3.6.jar` etc. (in WEB-INF/lib)

**Comment by aschneebauer** [comment]
With this settings it looks like that it works i got no issue any more. but i dont get any response. i send a testcall,
..deliverInvoice with a small byte example. I did it: 

Element node;
		try {
			node = DocumentBuilderFactory.newInstance().newDocumentBuilder()
					.parse(new ByteArrayInputStream("<node>value</node>".getBytes())).getDocumentElement();
			WS200Sender stub = new WS200Sender(sWebserviceUsername, sWebservicePassword);
			stub.setTestVersion(true);

			List<DeliveryEmbeddedAttachmentType> aAttachments = null;
			DeliverySettingsType aSettings = new DeliverySettingsType();
			stub.deliverInvoice(node, aAttachments, aSettings);			
		} catch (SAXException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ParserConfigurationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

**Comment by phax** [comment]
Use this
```java
final DeliveryResponseType aResult = stub.deliverInvoice(node, aAttachments, aSettings);
```
See test class https://github.com/phax/erechnung.gv.at-webservice-client/blob/master/src/test/java/com/helger/erechnung/erb/ws200/WS200SenderTest.java for an example

**Comment by aschneebauer** [comment]
> Use this
> 
> ```java
> final DeliveryResponseType aResult = stub.deliverInvoice(node, aAttachments, aSettings);
> ```
> 
> See test class https://github.com/phax/erechnung.gv.at-webservice-client/blob/master/src/test/java/com/helger/erechnung/erb/ws200/WS200SenderTest.java for an example

Thats it thanks. now i will play with jaxb to auto generate java class from xsd file and convert it to xml to send it via your interface.

**Comment by phax** [comment]
Good lucky and happy eInvoicing :)

**Comment by phax** [comment]
Please note, that the Webservice error codes of the gateway are very weird.
See https://www.erechnung.gv.at/erb?locale=de_AT&p=tec_delivery_ws&tab=errors for some interpretation help.
If you like the project, feel free to star it :)

**Comment by aschneebauer** [comment]
> Please note, that the Webservice error codes of the gateway are very weird.
> See https://www.erechnung.gv.at/erb?locale=de_AT&p=tec_delivery_ws&tab=errors for some interpretation help.
> If you like the project, feel free to star it :)

sure Thanks for helping
